USE_CAMERA_STUB := true

BOARD_USES_GENERIC_AUDIO := true
BOARD_FIRST_CAMERA_FRONT_FACING := true


# inherit from the proprietary version
-include vendor/andypad/andypadpro/BoardConfigVendor.mk
BOARD_USES_GENERIC_AUDIO := false
BOARD_PREBUILT_LIBAUDIO := true



TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := andypadpro
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOOTLOADER_BOARD_NAME := rk29board

TARGET_PROVIDES_INIT_RC := true

TARGET_NO_KERNEL := true

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00400000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00800000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x10000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x40000000
BOARD_FLASH_BLOCK_SIZE := 16384

WPA_SUPPLICANT_VERSION := VER_0_6_X
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WIFI_DRIVER_MODULE_PATH     := "/system/lib/modules/wlan.ko"
WIFI_DRIVER_MODULE_ARG      := ""
WIFI_DRIVER_MODULE_NAME     := "wlan"

BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

BOARD_HAVE_FM_RADIO := false

BOARD_EGL_CFG := device/andypad/andypadpro/egl.cfg
BOARD_NO_RGBX_8888 := true
TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true

TARGET_OVERLAY_ALWAYS_DETERMINES_FORMAT := true

WITH_JIT := true
JS_ENGINE := v8



