#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=andypadpro
MANUFACTURER=andypad

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary

	adb pull /rk29xxnand_ko.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk29xxnand_ko.ko

	adb pull /system/lib/egl/libEGL_VIVANTE.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libEGL_VIVANTE.so
	adb pull /system/lib/egl/libGLESv1_CM_VIVANTE.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv1_CM_VIVANTE.so
	adb pull /system/lib/egl/libGLESv2_VIVANTE.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2_VIVANTE.so
	adb pull /system/lib/hw/copybit.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/copybit.rk29board.so
	adb pull /system/lib/hw/gralloc.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gralloc.rk29board.so
	adb pull /system/lib/hw/lights.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lights.rk29board.so
	adb pull /system/lib/hw/overlay.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/overlay.rk29board.so
	adb pull /system/lib/hw/sensors.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sensors.rk29board.so
	adb pull /system/lib/libGAL.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGAL.so
	adb pull /system/lib/libGLESv2SC.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2SC.so
	adb pull /system/lib/libaudio.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudio.so
	adb pull /system/lib/libaudiopolicy.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudiopolicy.so
	adb pull /system/lib/libcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libcamera.so
	adb pull /system/lib/libjpeghwdec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libjpeghwdec.so
	adb pull /system/lib/libjpeghwenc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libjpeghwenc.so
	adb pull /system/lib/libvpu.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libvpu.so
	adb pull /system/lib/modules/wlan.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wlan.ko
	adb pull /system/lib/libreference-cdma-sms.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
	adb pull /system/lib/libreference-ril.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
	adb pull /system/lib/libril-rk29-dataonly.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/

	adb pull /system/bin/usb_modeswitch ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usb_modeswitch
	adb pull /system/bin/akmd8975 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/akmd8975


	adb pull /system/etc/rockchip_bq27510.bqfs ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rockchip_bq27510.bqfs
	adb pull /system/etc/rockchip_bq27510.dffs ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rockchip_bq27510.dffs
	adb pull /system/etc/firmware/athtcmd_ram.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/athtcmd_ram.bin
	adb pull /system/etc/firmware/athwlan.bin.z77 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/athwlan.bin.z77
	adb pull /system/etc/firmware/data.patch.hw2_0.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/data.patch.hw2_0.bin
	adb pull /system/etc/firmware/calData_ar6102_15dBm.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/calData_ar6102_15dBm.bin
	adb pull /system/etc/firmware/device.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/device.bin
	adb pull /system/etc/firmware/fw_bcm4329.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/fw_bcm4329.bin
	adb pull /system/etc/firmware/fw_bcm4329_apsta.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/fw_bcm4329_apsta.bin
	adb pull /system/etc/firmware/nvram_B23.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/nvram_B23.txt
	adb pull /system/etc/firmware/sd8686.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/sd8686.bin
	adb pull /system/etc/firmware/sd8686_helper.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/sd8686_helper.bin
	adb pull /system/etc/firmware/softmac../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/softmac
	adb pull /system/etc/gameloft_info.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gameloft_info.xml
	adb pull /system/etc/media_profiles.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/media_profiles.xml
	adb pull /system/etc/usb_modeswitch.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usb_modeswitch.sh





(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudio.so:obj/lib/libaudio.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudiopolicy.so:obj/lib/libaudiopolicy.so

# All the blobs necessary for andypadpro
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk29xxnand_ko.ko:root/lib/modules/rk29xxnand_ko.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/copybit.rk29board.so:system/lib/hw/copybit.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gralloc.rk29board.so:system/lib/hw/gralloc.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/lights.rk29board.so:system/lib/hw/lights.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/overlay.rk29board.so:system/lib/hw/overlay.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sensors.rk29board.so:system/lib/hw/sensors.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGAL.so:system/lib/libGAL.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2SC.so:system/lib/libGLESv2SC.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudio.so:system/lib/libaudio.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudiopolicy.so:system/lib/libaudiopolicy.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wlan.ko:system/lib/modules/wlan.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gameloft_info.xml:system/etc/gameloft_info.xml \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/media_profiles.xml:system/etc/media_profiles.xml \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usb_modeswitch.sh:system/etc/usb_modeswitch.sh \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/akmd8975:system/bin/akmd8975 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rockchip_bq27510.bqfs:system/etc/rockchip_bq27510.bqfs \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rockchip_bq27510.dffs:system/etc/rockchip_bq27510.dffs \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcamera.so:system/lib/libcamera.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libjpeghwdec.so:system/lib/libjpeghwdec.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libjpeghwenc.so:system/lib/libjpeghwenc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libvpu.so:system/lib/libvpu.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usb_modeswitch:system/bin/usb_modeswitch \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libreference-cdma-sms.so:system/lib/libreference-cdma-sms.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libreference-ril.so:system/lib/libreference-ril.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libril-rk29-dataonly.so:system/lib/libril-rk29-dataonly.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/athtcmd_ram.bin:system/etc/firmware/athtcmd_ram.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/athwlan.bin.z77:system/etc/firmware/athwlan.bin.z77 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/calData_ar6102_15dBm.bin:system/etc/firmware/calData_ar6102_15dBm.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/device.bin:system/etc/firmware/device.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/nvram_B23.txt:system/etc/firmware/nvram_B23.txt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/sd8686.bin:system/etc/firmware/sd8686.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/sd8686_helper.bin:system/etc/firmware/sd8686_helper.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/softmac:system/etc/firmware/softmac \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/data.patch.hw2_0.bin:system/etc/firmware/data.patch.hw2_0.bin


EOF

./setup-makefiles.sh
