#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=andypadpro
MANUFACTURER=andypad

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary

	adb pull /rk29xxnand_ko.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk29xxnand_ko.ko

	adb pull /system/lib/egl/libEGL_VIVANTE.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libEGL_VIVANTE.so
	adb pull /system/lib/egl/libGLESv1_CM_VIVANTE.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv1_CM_VIVANTE.so
	adb pull /system/lib/egl/libGLESv2_VIVANTE.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2_VIVANTE.so
	adb pull /system/lib/hw/copybit.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/copybit.rk29board.so
	adb pull /system/lib/hw/gralloc.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gralloc.rk29board.so
	adb pull /system/lib/hw/lights.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lights.rk29board.so
	adb pull /system/lib/hw/overlay.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/overlay.rk29board.so
	adb pull /system/lib/hw/sensors.rk29board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sensors.rk29board.so
	adb pull /system/lib/libGAL.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGAL.so
	adb pull /system/lib/libGLESv2SC.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2SC.so
	adb pull /system/lib/libaudio.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudio.so
	adb pull /system/lib/libaudiopolicy.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudiopolicy.so
	adb pull /system/lib/libcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libcamera.so
	adb pull /system/lib/libjpeghwdec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libjpeghwdec.so
	adb pull /system/lib/libjpeghwenc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libjpeghwenc.so
	adb pull /system/lib/libvpu.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libvpu.so
	adb pull /system/lib/modules/wlan.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wlan.ko
	adb pull /system/lib/libreference-cdma-sms.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
	adb pull /system/lib/libreference-ril.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
	adb pull /system/lib/libril-rk29-dataonly.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/

	adb pull /system/bin/usb_modeswitch ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usb_modeswitch
	adb pull /system/bin/akmd8975 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/akmd8975
	adb pull /system/bin/hdmi_init ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/hdmi_init
	adb pull /system/bin/wlan_loader ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wlan_loader
	adb pull /system/bin/wlan_mac ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wlan_mac
	adb pull /system/bin/brcm_patchram_plus ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/brcm_patchram_plus

	adb pull /system/etc/rockchip_bq27510.bqfs ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rockchip_bq27510.bqfs
	adb pull /system/etc/rockchip_bq27510.dffs ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rockchip_bq27510.dffs
	adb pull /system/etc/firmware/athtcmd_ram.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/athtcmd_ram.bin
	adb pull /system/etc/firmware/athwlan.bin.z77 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/athwlan.bin.z77
	adb pull /system/etc/firmware/data.patch.hw2_0.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/data.patch.hw2_0.bin
	adb pull /system/etc/firmware/calData_ar6102_15dBm.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/calData_ar6102_15dBm.bin
	adb pull /system/etc/firmware/device.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/device.bin
	adb pull /system/etc/firmware/fw_bcm4329.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/fw_bcm4329.bin
	adb pull /system/etc/firmware/fw_bcm4329_apsta.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/fw_bcm4329_apsta.bin
	adb pull /system/etc/firmware/nvram_B23.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/nvram_B23.txt
	adb pull /system/etc/firmware/sd8686.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/sd8686.bin
	adb pull /system/etc/firmware/sd8686_helper.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/sd8686_helper.bin
	adb pull /system/etc/firmware/softmac../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/softmac
	adb pull /system/etc/gameloft_info.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gameloft_info.xml
	adb pull /system/etc/media_profiles.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/media_profiles.xml
	adb pull /system/etc/usb_modeswitch.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usb_modeswitch.sh
	adb pull /system/etc/bluez/bcm432x/BCM4329B1_TestOnly_0237_26MHz_SEMCO_B23.hcd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/BCM4329B1_TestOnly_0237_26MHz_SEMCO_B23.hcd


#these might not be needed.. need to experiment :)
	adb pull /system/bin/i2c ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/i2c
	adb pull /system/bin/patch_plus ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/patch_plus
	adb pull /system/bin/pretest ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pretest
	adb pull /system/bin/usb_modeswitch ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usb_modeswitch
	adb pull /system/bin/wlarm_android ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wlarm_android

	adb pull /system/framework/android.rockchip.hdmi.jar ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/android.rockchip.hdmi.jar
	adb pull /system/framework/android.rockchip.manager.jar ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/android.rockchip.manager.jar
	adb pull /system/framework/android.rockchip.tvout.jar ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/android.rockchip.tvout.jar
	adb pull /system/framework/android.rockchip.update.jar ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/android.rockchip.update.jar

	adb pull /system/lib/librockchip_hdmi_jni.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/android.rockchip.update.jar
	adb pull /system/lib/librockchip_tvout_jni.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/android.rockchip.update.jar
	adb pull /system/lib/librockchip_update_jni.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/android.rockchip.update.jar

	adb pull /system/xbin/dhdutil ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dhdutil
	adb pull /system/xbin/io ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/io
	adb pull /system/xbin/script_parse ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/script_parse
#end of these might not be needed..


#hw video playback. Again, not sure these are all needed (esp. the codecs)
	adb pull /system/lib/lib_rk_apedec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib_rk_apedec.so
adb pull /system/lib/lib_rk_flacdec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lib_rk_flacdec.so
adb pull /system/lib/stagefright.ver ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/stagefright.ver
adb pull /system/lib/libstagefrighthw.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libstagefrighthw.so
adb pull /system/lib/libRkDeflatingDecompressor.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libRkDeflatingDecompressor.so
adb pull /system/lib/opencore.ver ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/opencore.ver
adb pull /system/lib/pvplayer.cfg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pvplayer.cfg
adb pull /system/lib/libopencorehw.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencorehw.so
adb pull /system/lib/libopencore_wmvlocalreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_wmvlocalreg.so
adb pull /system/lib/libopencore_wmvlocal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_wmvlocal.so
adb pull /system/lib/libopencore_webmlocalreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_webmlocalreg.so
adb pull /system/lib/libopencore_webmlocal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_webmlocal.so
adb pull /system/lib/libopencore_rtspreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_rtspreg.so
adb pull /system/lib/libopencore_rtsp.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_rtsp.so
adb pull /system/lib/libopencore_rmlocalreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_rmlocalreg.so
adb pull /system/lib/libopencore_rmlocal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_rmlocal.so
adb pull /system/lib/libopencore_player.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_player.so
adb pull /system/lib/libopencore_net_support.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_net_support.so
adb pull /system/lib/libopencore_mpglocalreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_mpglocalreg.so
adb pull /system/lib/libopencore_mpglocal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_mpglocal.so
adb pull /system/lib/libopencore_mp4localreg.so../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_mp4localreg.so
adb pull /system/lib/libopencore_mp4local.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_mp4local.so
adb pull /system/lib/libopencore_mkvlocalreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_mkvlocalreg.so
adb pull /system/lib/libopencore_mkvlocal.so../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_mkvlocal.so
adb pull /system/lib/libopencore_flvlocalreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_flvlocalreg.so
adb pull /system/lib/libopencore_flvlocal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_flvlocal.so
adb pull /system/lib/libopencore_downloadreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_downloadreg.so
adb pull /system/lib/libopencore_download.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_download.so
adb pull /system/lib/libopencore_common.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_common.so
adb pull /system/lib/libopencore_avilocalreg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_avilocalreg.so
adb pull /system/lib/libopencore_avilocal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_avilocal.so
adb pull /system/lib/libopencore_author.so../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libopencore_author.so
adb pull /system/lib/libomx_wmvdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_wmvdec_sharedlibrary.so
adb pull /system/lib/libomx_wmadec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_wmadec_sharedlibrary.so
adb pull /system/lib/libomx_wavdec_sharedlibrary.so../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_wavdec_sharedlibrary.so
adb pull /system/lib/libomx_vp8dec_sharedlibrary.so../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_vp8dec_sharedlibrary.so
adb pull /system/lib/libomx_sharedlibrary.so../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_sharedlibrary.so
adb pull /system/lib/libomx_rmdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_rmdec_sharedlibrary.so
adb pull /system/lib/libomx_radec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_radec_sharedlibrary.so
adb pull /system/lib/libomx_oggdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_oggdec_sharedlibrary.so
adb pull /system/lib/libomx_mp3dec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_mp3dec_sharedlibrary.so
adb pull /system/lib/libomx_m4venc_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_m4venc_sharedlibrary.so
adb pull /system/lib/libomx_m4vdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_m4vdec_sharedlibrary.so
adb pull /system/lib/libomx_m2vdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_m2vdec_sharedlibrary.so
adb pull /system/lib/libomx_flv1dec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_flv1dec_sharedlibrary.so
adb pull /system/lib/libomx_dtsdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_dtsdec_sharedlibrary.so
adb pull /system/lib/libomx_dradec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_dradec_sharedlibrary.so
adb pull /system/lib/libomx_avcenc_sharedlibrary.so../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_avcenc_sharedlibrary.so
adb pull /system/lib/libomx_avcdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_avcdec_sharedlibrary.so
adb pull /system/lib/libomx_amrenc_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_amrenc_sharedlibrary.so
adb pull /system/lib/libomx_amrdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_amrdec_sharedlibrary.so
adb pull /system/lib/libomx_ac3dec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_ac3dec_sharedlibrary.so
adb pull /system/lib/libomx_aacdec_sharedlibrary.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libomx_aacdec_sharedlibrary.so
# end of hw video playback

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudio.so:obj/lib/libaudio.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudiopolicy.so:obj/lib/libaudiopolicy.so

# All the blobs necessary for andypadpro
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk29xxnand_ko.ko:root/lib/modules/rk29xxnand_ko.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/copybit.rk29board.so:system/lib/hw/copybit.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gralloc.rk29board.so:system/lib/hw/gralloc.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/lights.rk29board.so:system/lib/hw/lights.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/overlay.rk29board.so:system/lib/hw/overlay.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sensors.rk29board.so:system/lib/hw/sensors.rk29board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGAL.so:system/lib/libGAL.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2SC.so:system/lib/libGLESv2SC.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudio.so:system/lib/libaudio.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudiopolicy.so:system/lib/libaudiopolicy.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wlan.ko:system/lib/modules/wlan.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gameloft_info.xml:system/etc/gameloft_info.xml \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/media_profiles.xml:system/etc/media_profiles.xml \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usb_modeswitch.sh:system/etc/usb_modeswitch.sh \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/akmd8975:system/bin/akmd8975 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/i2c:system/bin/i2c  \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/patch_plus:system/bin/patch_plus \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/pretest:system/bin/pretest \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usb_modeswitch:system/bin/usb_modeswitch \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wlarm_android:system/bin/wlarm_android \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dhdutil:system/xbin/dhdutil \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/io:system/xbin/io \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/script_parse:system/xbin/script_parse \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rockchip_bq27510.bqfs:system/etc/rockchip_bq27510.bqfs \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rockchip_bq27510.dffs:system/etc/rockchip_bq27510.dffs \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcamera.so:system/lib/libcamera.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libjpeghwdec.so:system/lib/libjpeghwdec.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libjpeghwenc.so:system/lib/libjpeghwenc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libvpu.so:system/lib/libvpu.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libreference-cdma-sms.so:system/lib/libreference-cdma-sms.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libreference-ril.so:system/lib/libreference-ril.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libril-rk29-dataonly.so:system/lib/libril-rk29-dataonly.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/librockchip_hdmi_jni.so:system/lib/librockchip_hdmi_jni.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/librockchip_tvout_jni.so:system/lib/librockchip_tvout_jni.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/librockchip_update_jni.so:system/lib/librockchip_update_jni.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/android.rockchip.hdmi.jar:system/framework/android.rockchip.hdmi.jar \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/android.rockchip.manager.jar:system/framework/android.rockchip.manager.jar \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/android.rockchip.tvout.jar:system/framework/android.rockchip.tvout.jar\\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/android.rockchip.update.jar:system/framework/android.rockchip.update.jar \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/athtcmd_ram.bin:system/etc/firmware/athtcmd_ram.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/athwlan.bin.z77:system/etc/firmware/athwlan.bin.z77 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/calData_ar6102_15dBm.bin:system/etc/firmware/calData_ar6102_15dBm.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/device.bin:system/etc/firmware/device.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/nvram_B23.txt:system/etc/firmware/nvram_B23.txt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/sd8686.bin:system/etc/firmware/sd8686.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/sd8686_helper.bin:system/etc/firmware/sd8686_helper.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/softmac:system/etc/firmware/softmac \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/data.patch.hw2_0.bin:system/etc/firmware/data.patch.hw2_0.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/hdmi_init:system/bin/hdmi_init \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wlan_loader:system/bin/wlan_loader \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wlan_mac:system/bin/wlan_mac \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/brcm_patchram_plus:system/bin/brcm_patchram_plus \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/BCM4329B1_TestOnly_0237_26MHz_SEMCO_B23.hcd:system/etc/bluez/bcm432x/BCM4329B1_TestOnly_0237_26MHz_SEMCO_B23.hcd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/shutdown:system/bin/shutdown

EOF

./setup-makefiles.sh
